/**
 * Institutions offered in the onboarding wizard's university combobox.
 *
 * This list is a convenience, never a constraint. India alone has well over
 * 40,000 colleges, so any shippable list is wrong for somebody — which is why
 * the field keeps a free-text escape hatch and the server validates only the
 * length of what arrives, not its membership here (see `validations/profile`).
 * A student at a college we have never heard of must still be able to finish
 * signing up.
 *
 * Names are stored the way students actually write them — "IIT Bombay", not
 * "Indian Institute of Technology Bombay" — because the combobox filters on a
 * plain substring match, so the label is also the search key. Where the long
 * form is what someone would type, the short form follows in brackets.
 *
 * Source order below is grouped for the humans who maintain it; the export is
 * de-duplicated and sorted once at module load, because a flat alphabetical
 * list is what the combobox renders before anyone types (see the design note:
 * flat searchable lists, not grouped section headers).
 */

const INDIAN_INSTITUTES_OF_TECHNOLOGY = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT (BHU) Varanasi",
  "IIT Gandhinagar",
  "IIT Ropar",
  "IIT Patna",
  "IIT Bhubaneswar",
  "IIT Mandi",
  "IIT Jodhpur",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIT Dharwad",
  "IIT (ISM) Dhanbad",
];

const NATIONAL_INSTITUTES_OF_TECHNOLOGY = [
  "NIT Tiruchirappalli (NIT Trichy)",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Calicut",
  "NIT Rourkela",
  "NIT Durgapur",
  "NIT Kurukshetra",
  "NIT Jamshedpur",
  "NIT Silchar",
  "NIT Hamirpur",
  "NIT Jalandhar",
  "NIT Patna",
  "NIT Raipur",
  "NIT Srinagar",
  "NIT Agartala",
  "NIT Delhi",
  "NIT Goa",
  "NIT Manipur",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Puducherry",
  "NIT Sikkim",
  "NIT Uttarakhand",
  "NIT Andhra Pradesh",
  "NIT Arunachal Pradesh",
  "MNNIT Allahabad",
  "MANIT Bhopal",
  "VNIT Nagpur",
  "MNIT Jaipur",
  "SVNIT Surat",
];

const INDIAN_IIITS = [
  "IIIT Hyderabad",
  "IIIT Allahabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "ABV-IIITM Gwalior",
  "IIIT Jabalpur",
  "IIITDM Kancheepuram",
  "IIIT Lucknow",
  "IIIT Pune",
  "IIIT Nagpur",
  "IIIT Vadodara",
  "IIIT Kota",
  "IIIT Sri City",
  "IIIT Una",
  "IIIT Sonepat",
  "IIIT Guwahati",
  "IIIT Kalyani",
  "IIIT Dharwad",
  "IIIT Bhagalpur",
  "IIIT Surat",
  "IIIT Bhopal",
  "IIIT Ranchi",
  "IIIT Agartala",
  "IIIT Raichur",
  "IIIT Manipur",
  "IIIT Kottayam",
  "IIIT Tiruchirappalli",
];

const INDIAN_RESEARCH_AND_MANAGEMENT = [
  "Indian Institute of Science (IISc) Bangalore",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  "Indian Statistical Institute (ISI)",
  "Chennai Mathematical Institute",
  "Tata Institute of Fundamental Research (TIFR)",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Indore",
  "IIM Kozhikode",
  "IIM Shillong",
  "IIM Rohtak",
  "IIM Ranchi",
  "IIM Raipur",
  "IIM Tiruchirappalli",
  "IIM Udaipur",
  "IIM Kashipur",
  "IIM Nagpur",
  "IIM Visakhapatnam",
  "IIM Bodh Gaya",
  "IIM Amritsar",
  "IIM Sambalpur",
  "IIM Jammu",
  "XLRI Jamshedpur",
  "Management Development Institute (MDI) Gurgaon",
  "SP Jain Institute of Management and Research",
  "Narsee Monjee Institute of Management Studies (NMIMS)",
  "Indian Institute of Foreign Trade (IIFT)",
  "Tata Institute of Social Sciences (TISS)",
  "Symbiosis Institute of Business Management",
];

const INDIAN_PRIVATE_AND_DEEMED = [
  "BITS Pilani",
  "BITS Pilani, Goa Campus",
  "BITS Pilani, Hyderabad Campus",
  "BITS Pilani, Dubai Campus",
  "VIT Vellore",
  "VIT-AP University",
  "VIT Bhopal University",
  "SRM Institute of Science and Technology, Chennai",
  "SRM University, Amaravati",
  "Manipal Institute of Technology (MIT Manipal)",
  "Manipal University Jaipur",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Amrita Vishwa Vidyapeetham, Amritapuri",
  "Amrita Vishwa Vidyapeetham, Bengaluru",
  "Thapar Institute of Engineering and Technology",
  "Lovely Professional University (LPU)",
  "Chitkara University",
  "Chandigarh University",
  "Shiv Nadar University",
  "Ashoka University",
  "O.P. Jindal Global University",
  "Bennett University",
  "Jaypee Institute of Information Technology (JIIT) Noida",
  "Amity University, Noida",
  "Amity University, Jaipur",
  "Galgotias University",
  "Sharda University",
  "Graphic Era University",
  "Christ University, Bangalore",
  "PES University",
  "Dayananda Sagar College of Engineering",
  "Nitte Meenakshi Institute of Technology",
  "BNM Institute of Technology",
  "New Horizon College of Engineering",
  "Mahindra University",
  "Vignan's Foundation for Science, Technology and Research",
  "KL University (Koneru Lakshmaiah)",
  "GITAM University",
  "Kalinga Institute of Industrial Technology (KIIT)",
  "Siksha 'O' Anusandhan (SOA) University",
  "Symbiosis Institute of Technology, Pune",
  "MIT World Peace University, Pune",
  "MIT Art, Design and Technology University, Pune",
  "DY Patil College of Engineering, Pune",
  "Bharati Vidyapeeth, Pune",
  "Nirma University",
  "Pandit Deendayal Energy University (PDEU)",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)",
  "CHARUSAT University",
  "Marwadi University",
  "Parul University",
  "Ahmedabad University",
  "LNM Institute of Information Technology (LNMIIT) Jaipur",
  "JECRC University",
  "Poornima College of Engineering",
  "Vellore Institute of Technology, Chennai",
  "Sathyabama Institute of Science and Technology",
  "Hindustan Institute of Technology and Science",
  "Karunya Institute of Technology and Sciences",
  "SASTRA Deemed University",
  "Kumaraguru College of Technology",
  "Sri Krishna College of Engineering and Technology",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute",
  "Saveetha Engineering College",
  "Rajalakshmi Engineering College",
  "St. Joseph's College of Engineering, Chennai",
  "Rajagiri School of Engineering and Technology",
  "Federal Institute of Science and Technology (FISAT)",
  "SCMS School of Engineering and Technology",
  "Mar Athanasius College of Engineering",
  "Heritage Institute of Technology, Kolkata",
  "Techno Main Salt Lake",
  "Institute of Engineering and Management (IEM), Kolkata",
  "Manav Rachna University",
  "The NorthCap University",
  "Jaypee University of Engineering and Technology",
  "Alliance University",
  "Presidency University, Bangalore",
  "Reva University",
  "CMR Institute of Technology",
  "Acharya Institute of Technology",
  "Atria Institute of Technology",
];

const INDIAN_GOVERNMENT_ENGINEERING = [
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
  "Guru Gobind Singh Indraprastha University (GGSIPU)",
  "Jamia Millia Islamia",
  "Jamia Hamdard",
  "Anna University, Chennai",
  "College of Engineering, Guindy (CEG)",
  "Madras Institute of Technology (MIT Chromepet)",
  "PSG College of Technology",
  "Sri Sivasubramaniya Nadar College of Engineering (SSN)",
  "Thiagarajar College of Engineering",
  "Coimbatore Institute of Technology",
  "Government College of Technology, Coimbatore",
  "Jadavpur University",
  "Indian Institute of Engineering Science and Technology (IIEST) Shibpur",
  "Veermata Jijabai Technological Institute (VJTI)",
  "Institute of Chemical Technology (ICT) Mumbai",
  "Sardar Patel Institute of Technology (SPIT)",
  "K. J. Somaiya College of Engineering",
  "Dwarkadas J. Sanghvi College of Engineering",
  "Thadomal Shahani Engineering College",
  "College of Engineering, Pune (COEP)",
  "Pune Institute of Computer Technology (PICT)",
  "Vishwakarma Institute of Technology, Pune",
  "Cummins College of Engineering for Women",
  "Punjab Engineering College (PEC)",
  "R. V. College of Engineering (RVCE)",
  "B. M. S. College of Engineering (BMSCE)",
  "M. S. Ramaiah Institute of Technology (MSRIT)",
  "Sir M. Visvesvaraya Institute of Technology",
  "University Visvesvaraya College of Engineering (UVCE)",
  "JSS Science and Technology University, Mysuru",
  "Sri Jayachamarajendra College of Engineering (SJCE)",
  "The National Institute of Engineering (NIE) Mysuru",
  "KLE Technological University, Hubballi",
  "SDM College of Engineering and Technology",
  "Osmania University College of Engineering",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "JNTU Anantapur",
  "Chaitanya Bharathi Institute of Technology (CBIT)",
  "Vasavi College of Engineering",
  "VNR Vignana Jyothi Institute of Engineering and Technology",
  "Gokaraju Rangaraju Institute of Engineering and Technology",
  "Sreenidhi Institute of Science and Technology",
  "CVR College of Engineering",
  "Maturi Venkata Subba Rao (MVSR) Engineering College",
  "V. R. Siddhartha Engineering College",
  "R.V.R. & J.C. College of Engineering",
  "College of Engineering, Trivandrum (CET)",
  "TKM College of Engineering",
  "Government Engineering College, Thrissur",
  "Model Engineering College, Kochi",
  "Cochin University of Science and Technology (CUSAT)",
  "Harcourt Butler Technical University (HBTU) Kanpur",
  "Madan Mohan Malaviya University of Technology (MMMUT)",
  "Institute of Engineering and Technology (IET) Lucknow",
  "Bundelkhand Institute of Engineering and Technology",
  "Dr. A.P.J. Abdul Kalam Technical University (AKTU)",
  "Veer Surendra Sai University of Technology (VSSUT) Burla",
  "College of Engineering and Technology (CET) Bhubaneswar",
  "Birla Institute of Technology (BIT) Mesra",
  "L. D. College of Engineering",
  "Gujarat Technological University (GTU)",
  "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
  "Jabalpur Engineering College",
  "Samrat Ashok Technological Institute (SATI)",
  "Deenbandhu Chhotu Ram University of Science and Technology (DCRUST)",
  "Guru Jambheshwar University of Science and Technology",
  "Shri Mata Vaishno Devi University (SMVDU)",
  "Visvesvaraya Technological University (VTU)",
];

const INDIAN_UNIVERSITIES_GENERAL = [
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "University of Mumbai",
  "Savitribai Phule Pune University (SPPU)",
  "University of Calcutta",
  "University of Madras",
  "Bangalore University",
  "University of Hyderabad",
  "Osmania University",
  "Andhra University",
  "Sri Venkateswara University, Tirupati",
  "University of Kerala",
  "Mahatma Gandhi University, Kottayam",
  "University of Calicut",
  "University of Rajasthan",
  "Panjab University",
  "Guru Nanak Dev University",
  "Punjabi University, Patiala",
  "Kurukshetra University",
  "Maharshi Dayanand University (MDU) Rohtak",
  "Chaudhary Charan Singh University, Meerut",
  "University of Lucknow",
  "University of Allahabad",
  "Patna University",
  "Ranchi University",
  "Utkal University",
  "Gauhati University",
  "Tezpur University",
  "Assam University",
  "North-Eastern Hill University (NEHU)",
  "Manipur University",
  "Mizoram University",
  "Nagaland University",
  "Sikkim University",
  "University of Kashmir",
  "University of Jammu",
  "Visva-Bharati University",
  "Presidency University, Kolkata",
  "Pondicherry University",
  "Ambedkar University Delhi",
  "Maharaja Sayajirao University of Baroda",
  "Mangalore University",
  "University of Mysore",
  "Karnatak University, Dharwad",
  "Shivaji University, Kolhapur",
  "Bharathiar University",
  "Bharathidasan University",
  "Alagappa University",
  "Periyar University",
  "Annamalai University",
];

const INDIAN_COLLEGES_ARTS_COMMERCE_SCIENCE = [
  "St. Stephen's College, Delhi",
  "Shri Ram College of Commerce (SRCC)",
  "Hindu College, Delhi",
  "Hansraj College, Delhi",
  "Miranda House, Delhi",
  "Lady Shri Ram College for Women (LSR)",
  "Kirori Mal College, Delhi",
  "Ramjas College, Delhi",
  "Sri Venkateswara College, Delhi",
  "Gargi College, Delhi",
  "Jesus and Mary College, Delhi",
  "St. Xavier's College, Mumbai",
  "St. Xavier's College, Kolkata",
  "St. Joseph's University, Bengaluru",
  "Mount Carmel College, Bengaluru",
  "Loyola College, Chennai",
  "Madras Christian College (MCC)",
  "Stella Maris College, Chennai",
  "Presidency College, Chennai",
  "Fergusson College, Pune",
  "Symbiosis College of Arts and Commerce",
  "Sydenham College of Commerce and Economics",
  "Narsee Monjee College of Commerce and Economics",
  "H. R. College of Commerce and Economics",
  "Ramnarain Ruia Autonomous College",
  "Scottish Church College, Kolkata",
  "Christ College, Irinjalakuda",
  "Hislop College, Nagpur",
];

const INDIAN_PROFESSIONAL_SCHOOLS = [
  "All India Institute of Medical Sciences (AIIMS), New Delhi",
  "Christian Medical College (CMC) Vellore",
  "JIPMER Puducherry",
  "Armed Forces Medical College (AFMC)",
  "King George's Medical University (KGMU)",
  "Maulana Azad Medical College (MAMC)",
  "Seth G. S. Medical College (KEM Hospital)",
  "Grant Medical College, Mumbai",
  "St. John's Medical College, Bengaluru",
  "Kasturba Medical College, Manipal",
  "Lady Hardinge Medical College",
  "Bangalore Medical College and Research Institute",
  "National Law School of India University (NLSIU) Bangalore",
  "NALSAR University of Law, Hyderabad",
  "National Law University (NLU) Delhi",
  "West Bengal National University of Juridical Sciences (WBNUJS)",
  "National Law University, Jodhpur",
  "Gujarat National Law University (GNLU)",
  "Symbiosis Law School, Pune",
  "ILS Law College, Pune",
  "Faculty of Law, University of Delhi",
  "Government Law College, Mumbai",
  "National Institute of Design (NID)",
  "National Institute of Fashion Technology (NIFT)",
  "School of Planning and Architecture (SPA) Delhi",
  "Sir J. J. College of Architecture",
  "CEPT University",
  "Indian Institute of Hotel Management",
  "Indian Agricultural Research Institute (IARI)",
  "G. B. Pant University of Agriculture and Technology",
  "Punjab Agricultural University",
  "Tamil Nadu Agricultural University",
];

const UNITED_STATES = [
  "Massachusetts Institute of Technology (MIT)",
  "Stanford University",
  "Harvard University",
  "California Institute of Technology (Caltech)",
  "Carnegie Mellon University",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "University of California, San Diego",
  "University of California, Irvine",
  "University of California, Davis",
  "University of Illinois Urbana-Champaign",
  "Georgia Institute of Technology",
  "University of Michigan, Ann Arbor",
  "Cornell University",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "University of Chicago",
  "Johns Hopkins University",
  "Duke University",
  "Northwestern University",
  "New York University (NYU)",
  "University of Southern California (USC)",
  "University of Texas at Austin",
  "University of Wisconsin-Madison",
  "Purdue University",
  "University of Maryland, College Park",
  "University of Massachusetts Amherst",
  "Pennsylvania State University",
  "Ohio State University",
  "Texas A&M University",
  "Virginia Tech",
  "North Carolina State University",
  "Arizona State University",
  "Northeastern University",
  "Boston University",
  "Rice University",
  "Vanderbilt University",
  "University of Washington",
  "University of Minnesota",
  "University of Colorado Boulder",
  "Rutgers University",
  "Stony Brook University",
  "University at Buffalo",
  "University of Illinois Chicago",
  "University of Florida",
  "University of Georgia",
  "Indiana University Bloomington",
  "Syracuse University",
  "Clemson University",
  "Rochester Institute of Technology (RIT)",
  "Worcester Polytechnic Institute (WPI)",
  "Stevens Institute of Technology",
  "New Jersey Institute of Technology (NJIT)",
  "Illinois Institute of Technology",
  "Santa Clara University",
  "San Jose State University",
  "University of Utah",
  "University of Arizona",
];

const CANADA = [
  "University of Toronto",
  "University of Waterloo",
  "University of British Columbia",
  "McGill University",
  "University of Alberta",
  "McMaster University",
  "Western University",
  "Queen's University",
  "Simon Fraser University",
  "University of Ottawa",
  "University of Calgary",
  "Dalhousie University",
  "Concordia University",
  "York University",
  "Carleton University",
];

const UNITED_KINGDOM_AND_IRELAND = [
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "University of Edinburgh",
  "University of Manchester",
  "University of Warwick",
  "University of Bristol",
  "London School of Economics (LSE)",
  "King's College London",
  "University of Southampton",
  "University of Leeds",
  "University of Sheffield",
  "University of Glasgow",
  "University of Birmingham",
  "University of Nottingham",
  "Queen Mary University of London",
  "University of Bath",
  "Durham University",
  "Lancaster University",
  "University of Surrey",
  "Loughborough University",
  "Trinity College Dublin",
  "University College Dublin",
];

const EUROPE = [
  "ETH Zurich",
  "EPFL (École Polytechnique Fédérale de Lausanne)",
  "Technical University of Munich (TUM)",
  "Delft University of Technology (TU Delft)",
  "Technical University of Berlin (TU Berlin)",
  "RWTH Aachen University",
  "KTH Royal Institute of Technology",
  "Chalmers University of Technology",
  "Technical University of Denmark (DTU)",
  "Eindhoven University of Technology",
  "University of Amsterdam",
  "Utrecht University",
  "KU Leuven",
  "Sorbonne University",
  "École Polytechnique",
  "Politecnico di Milano",
  "Politecnico di Torino",
  "University of Bologna",
  "Universitat Politècnica de Catalunya (UPC)",
  "Aalto University",
  "TU Wien",
  "University of Copenhagen",
  "Lund University",
  "Heidelberg University",
];

const ASIA_PACIFIC = [
  "National University of Singapore (NUS)",
  "Nanyang Technological University (NTU) Singapore",
  "Singapore Management University",
  "Tsinghua University",
  "Peking University",
  "Fudan University",
  "Shanghai Jiao Tong University",
  "Zhejiang University",
  "University of Hong Kong (HKU)",
  "Hong Kong University of Science and Technology (HKUST)",
  "Chinese University of Hong Kong (CUHK)",
  "University of Tokyo",
  "Kyoto University",
  "Osaka University",
  "Tokyo Institute of Technology",
  "KAIST",
  "Seoul National University",
  "Yonsei University",
  "POSTECH",
  "University of Melbourne",
  "University of Sydney",
  "University of New South Wales (UNSW)",
  "Monash University",
  "Australian National University (ANU)",
  "University of Queensland",
  "University of Adelaide",
  "University of Technology Sydney (UTS)",
  "RMIT University",
  "University of Auckland",
];

const MIDDLE_EAST_AND_AFRICA = [
  "Technion - Israel Institute of Technology",
  "Tel Aviv University",
  "New York University Abu Dhabi",
  "American University of Sharjah",
  "Khalifa University",
  "Qatar University",
  "King Abdullah University of Science and Technology (KAUST)",
  "University of Cape Town",
  "University of the Witwatersrand",
  "Cairo University",
];

/**
 * De-duplicated and sorted once, at module load.
 *
 * The de-duplication is defensive rather than load-bearing: the groups above
 * overlap at the edges (a campus can plausibly be filed under two of them), and
 * a repeated entry should cost a maintainer nothing worse than one wasted line.
 */
export const UNIVERSITIES: readonly string[] = [
  ...new Set([
    ...INDIAN_INSTITUTES_OF_TECHNOLOGY,
    ...NATIONAL_INSTITUTES_OF_TECHNOLOGY,
    ...INDIAN_IIITS,
    ...INDIAN_RESEARCH_AND_MANAGEMENT,
    ...INDIAN_PRIVATE_AND_DEEMED,
    ...INDIAN_GOVERNMENT_ENGINEERING,
    ...INDIAN_UNIVERSITIES_GENERAL,
    ...INDIAN_COLLEGES_ARTS_COMMERCE_SCIENCE,
    ...INDIAN_PROFESSIONAL_SCHOOLS,
    ...UNITED_STATES,
    ...CANADA,
    ...UNITED_KINGDOM_AND_IRELAND,
    ...EUROPE,
    ...ASIA_PACIFIC,
    ...MIDDLE_EAST_AND_AFRICA,
  ]),
].sort((left, right) => left.localeCompare(right, "en"));
