/**
 * The seeded company list that backs autocomplete on the application form.
 *
 * India-weighted with strong global coverage, per DESIGN.md §9 — the target
 * user is applying to Indian IT services, Indian product companies and
 * startups, global tech, finance, consulting and core engineering.
 *
 * `website` is populated only where the canonical domain is unambiguous.
 * Guessing the rest would put wrong data in front of every user, and the field
 * is optional precisely so it can stay empty. Users can add it on companies
 * they create.
 *
 * Names use display casing. The match key is derived by normalizeCompanyName()
 * at seed time, so "Dr. Reddy's Laboratories" and "dr reddys laboratories"
 * cannot both end up as rows.
 */
export type SeedCompany = {
  name: string;
  website?: string;
};

export const SEED_COMPANIES: SeedCompany[] = [
  // -------------------------------------------------------------------------
  // Global technology and product
  // -------------------------------------------------------------------------
  { name: "Google", website: "https://www.google.com" },
  { name: "Microsoft", website: "https://www.microsoft.com" },
  { name: "Amazon", website: "https://www.amazon.com" },
  { name: "Apple", website: "https://www.apple.com" },
  { name: "Meta", website: "https://www.meta.com" },
  { name: "Netflix", website: "https://www.netflix.com" },
  { name: "Nvidia", website: "https://www.nvidia.com" },
  { name: "Adobe", website: "https://www.adobe.com" },
  { name: "Salesforce", website: "https://www.salesforce.com" },
  { name: "Oracle", website: "https://www.oracle.com" },
  { name: "IBM", website: "https://www.ibm.com" },
  { name: "Intel", website: "https://www.intel.com" },
  { name: "AMD", website: "https://www.amd.com" },
  { name: "Qualcomm", website: "https://www.qualcomm.com" },
  { name: "Cisco", website: "https://www.cisco.com" },
  { name: "Dell Technologies", website: "https://www.dell.com" },
  { name: "HP", website: "https://www.hp.com" },
  { name: "Hewlett Packard Enterprise", website: "https://www.hpe.com" },
  { name: "VMware", website: "https://www.vmware.com" },
  { name: "SAP", website: "https://www.sap.com" },
  { name: "ServiceNow", website: "https://www.servicenow.com" },
  { name: "Workday", website: "https://www.workday.com" },
  { name: "Atlassian", website: "https://www.atlassian.com" },
  { name: "Shopify", website: "https://www.shopify.com" },
  { name: "Spotify", website: "https://www.spotify.com" },
  { name: "Uber", website: "https://www.uber.com" },
  { name: "Airbnb", website: "https://www.airbnb.com" },
  { name: "Stripe", website: "https://www.stripe.com" },
  { name: "PayPal", website: "https://www.paypal.com" },
  { name: "Twilio", website: "https://www.twilio.com" },
  { name: "Snowflake", website: "https://www.snowflake.com" },
  { name: "Databricks", website: "https://www.databricks.com" },
  { name: "MongoDB", website: "https://www.mongodb.com" },
  { name: "Elastic", website: "https://www.elastic.co" },
  { name: "HashiCorp", website: "https://www.hashicorp.com" },
  { name: "GitLab", website: "https://about.gitlab.com" },
  { name: "GitHub", website: "https://github.com" },
  { name: "Docker", website: "https://www.docker.com" },
  { name: "Datadog", website: "https://www.datadoghq.com" },
  { name: "Cloudflare", website: "https://www.cloudflare.com" },
  { name: "Figma", website: "https://www.figma.com" },
  { name: "Notion", website: "https://www.notion.so" },
  { name: "Canva", website: "https://www.canva.com" },
  { name: "Slack", website: "https://slack.com" },
  { name: "Zoom", website: "https://zoom.us" },
  { name: "Dropbox", website: "https://www.dropbox.com" },
  { name: "Asana", website: "https://asana.com" },
  { name: "Miro", website: "https://miro.com" },
  { name: "Linear", website: "https://linear.app" },
  { name: "Vercel", website: "https://vercel.com" },
  { name: "Netlify", website: "https://www.netlify.com" },
  { name: "Supabase", website: "https://supabase.com" },
  { name: "Confluent", website: "https://www.confluent.io" },
  { name: "Palantir Technologies", website: "https://www.palantir.com" },
  { name: "Splunk", website: "https://www.splunk.com" },
  { name: "Okta", website: "https://www.okta.com" },
  { name: "CrowdStrike", website: "https://www.crowdstrike.com" },
  { name: "Zscaler", website: "https://www.zscaler.com" },
  { name: "Fortinet", website: "https://www.fortinet.com" },
  { name: "Palo Alto Networks", website: "https://www.paloaltonetworks.com" },
  { name: "SentinelOne", website: "https://www.sentinelone.com" },
  { name: "LinkedIn", website: "https://www.linkedin.com" },
  { name: "Pinterest", website: "https://www.pinterest.com" },
  { name: "Snap", website: "https://www.snap.com" },
  { name: "Reddit", website: "https://www.reddit.com" },
  { name: "Discord", website: "https://discord.com" },
  { name: "Roblox", website: "https://www.roblox.com" },
  { name: "Unity Technologies", website: "https://unity.com" },
  { name: "Electronic Arts", website: "https://www.ea.com" },
  { name: "Ubisoft", website: "https://www.ubisoft.com" },
  { name: "Epic Games", website: "https://www.epicgames.com" },
  { name: "Riot Games", website: "https://www.riotgames.com" },
  { name: "OpenAI", website: "https://openai.com" },
  { name: "Anthropic", website: "https://www.anthropic.com" },
  { name: "Hugging Face", website: "https://huggingface.co" },
  { name: "Grammarly", website: "https://www.grammarly.com" },
  { name: "Coursera", website: "https://www.coursera.org" },
  { name: "Udemy", website: "https://www.udemy.com" },
  { name: "Duolingo", website: "https://www.duolingo.com" },

  // -------------------------------------------------------------------------
  // Indian IT services, BPM and global delivery
  // -------------------------------------------------------------------------
  { name: "Tata Consultancy Services", website: "https://www.tcs.com" },
  { name: "Infosys", website: "https://www.infosys.com" },
  { name: "Wipro", website: "https://www.wipro.com" },
  { name: "HCLTech", website: "https://www.hcltech.com" },
  { name: "Tech Mahindra", website: "https://www.techmahindra.com" },
  { name: "LTIMindtree", website: "https://www.ltimindtree.com" },
  { name: "Mphasis", website: "https://www.mphasis.com" },
  { name: "Persistent Systems", website: "https://www.persistent.com" },
  { name: "Coforge", website: "https://www.coforge.com" },
  { name: "Hexaware Technologies", website: "https://hexaware.com" },
  { name: "Cyient", website: "https://www.cyient.com" },
  { name: "Zensar Technologies", website: "https://www.zensar.com" },
  { name: "Birlasoft", website: "https://www.birlasoft.com" },
  { name: "Happiest Minds Technologies", website: "https://www.happiestminds.com" },
  { name: "Sonata Software", website: "https://www.sonata-software.com" },
  { name: "Mastek", website: "https://www.mastek.com" },
  { name: "Newgen Software", website: "https://newgensoft.com" },
  { name: "KPIT Technologies", website: "https://www.kpit.com" },
  { name: "Tata Elxsi", website: "https://www.tataelxsi.com" },
  { name: "L&T Technology Services", website: "https://www.ltts.com" },
  { name: "Infosys BPM", website: "https://www.infosysbpm.com" },
  { name: "WNS Global Services", website: "https://www.wns.com" },
  { name: "Firstsource Solutions", website: "https://www.firstsource.com" },
  { name: "Genpact", website: "https://www.genpact.com" },
  { name: "EXL Service", website: "https://www.exlservice.com" },
  { name: "Concentrix", website: "https://www.concentrix.com" },
  { name: "Teleperformance", website: "https://www.teleperformance.com" },
  { name: "Quess Corp", website: "https://www.quesscorp.com" },
  { name: "Virtusa", website: "https://www.virtusa.com" },
  { name: "Nagarro", website: "https://www.nagarro.com" },
  { name: "Thoughtworks", website: "https://www.thoughtworks.com" },
  { name: "Globant", website: "https://www.globant.com" },
  { name: "EPAM Systems", website: "https://www.epam.com" },
  { name: "Cognizant", website: "https://www.cognizant.com" },
  { name: "Accenture", website: "https://www.accenture.com" },
  { name: "Capgemini", website: "https://www.capgemini.com" },
  { name: "DXC Technology", website: "https://dxc.com" },
  { name: "Atos", website: "https://atos.net" },
  { name: "NTT Data", website: "https://www.nttdata.com" },
  { name: "Unisys", website: "https://www.unisys.com" },

  // -------------------------------------------------------------------------
  // Indian product companies and startups
  // -------------------------------------------------------------------------
  { name: "Flipkart", website: "https://www.flipkart.com" },
  { name: "Myntra", website: "https://www.myntra.com" },
  { name: "Meesho", website: "https://www.meesho.com" },
  { name: "Nykaa", website: "https://www.nykaa.com" },
  { name: "Zomato", website: "https://www.zomato.com" },
  { name: "Swiggy", website: "https://www.swiggy.com" },
  { name: "Zepto", website: "https://www.zeptonow.com" },
  { name: "Blinkit", website: "https://blinkit.com" },
  { name: "BigBasket", website: "https://www.bigbasket.com" },
  { name: "Ola", website: "https://www.olacabs.com" },
  { name: "Ola Electric", website: "https://www.olaelectric.com" },
  { name: "Rapido", website: "https://rapido.bike" },
  { name: "OYO", website: "https://www.oyorooms.com" },
  { name: "MakeMyTrip", website: "https://www.makemytrip.com" },
  { name: "Goibibo", website: "https://www.goibibo.com" },
  { name: "Cleartrip", website: "https://www.cleartrip.com" },
  { name: "ixigo", website: "https://www.ixigo.com" },
  { name: "EaseMyTrip", website: "https://www.easemytrip.com" },
  { name: "RedBus", website: "https://www.redbus.in" },
  { name: "Paytm", website: "https://paytm.com" },
  { name: "PhonePe", website: "https://www.phonepe.com" },
  { name: "Razorpay", website: "https://razorpay.com" },
  { name: "CRED", website: "https://cred.club" },
  { name: "Groww", website: "https://groww.in" },
  { name: "Zerodha", website: "https://zerodha.com" },
  { name: "Upstox", website: "https://upstox.com" },
  { name: "Smallcase", website: "https://www.smallcase.com" },
  { name: "INDmoney", website: "https://www.indmoney.com" },
  { name: "Jupiter", website: "https://jupiter.money" },
  { name: "Fi Money", website: "https://fi.money" },
  { name: "Slice", website: "https://www.sliceit.com" },
  { name: "KreditBee", website: "https://www.kreditbee.in" },
  { name: "Navi", website: "https://navi.com" },
  { name: "Lendingkart", website: "https://www.lendingkart.com" },
  { name: "Pine Labs", website: "https://www.pinelabs.com" },
  { name: "Juspay", website: "https://juspay.io" },
  { name: "Cashfree Payments", website: "https://www.cashfree.com" },
  { name: "BharatPe", website: "https://bharatpe.com" },
  { name: "MobiKwik", website: "https://www.mobikwik.com" },
  { name: "Policybazaar", website: "https://www.policybazaar.com" },
  { name: "ACKO", website: "https://www.acko.com" },
  { name: "Digit Insurance", website: "https://www.godigit.com" },
  { name: "Turtlemint", website: "https://www.turtlemint.com" },
  { name: "BYJU'S", website: "https://byjus.com" },
  { name: "Unacademy", website: "https://unacademy.com" },
  { name: "Vedantu", website: "https://www.vedantu.com" },
  { name: "Physics Wallah", website: "https://www.pw.live" },
  { name: "upGrad", website: "https://www.upgrad.com" },
  { name: "Scaler", website: "https://www.scaler.com" },
  { name: "GeeksforGeeks", website: "https://www.geeksforgeeks.org" },
  { name: "Coding Ninjas", website: "https://www.codingninjas.com" },
  { name: "Simplilearn", website: "https://www.simplilearn.com" },
  { name: "Great Learning", website: "https://www.mygreatlearning.com" },
  { name: "Emeritus", website: "https://emeritus.org" },
  { name: "Zoho", website: "https://www.zoho.com" },
  { name: "Freshworks", website: "https://www.freshworks.com" },
  { name: "Chargebee", website: "https://www.chargebee.com" },
  { name: "Postman", website: "https://www.postman.com" },
  { name: "BrowserStack", website: "https://www.browserstack.com" },
  { name: "Hasura", website: "https://hasura.io" },
  { name: "Whatfix", website: "https://whatfix.com" },
  { name: "MoEngage", website: "https://www.moengage.com" },
  { name: "CleverTap", website: "https://clevertap.com" },
  { name: "WebEngage", website: "https://webengage.com" },
  { name: "Netcore Cloud", website: "https://netcorecloud.com" },
  { name: "Darwinbox", website: "https://darwinbox.com" },
  { name: "Keka", website: "https://www.keka.com" },
  { name: "Innovaccer", website: "https://innovaccer.com" },
  { name: "HealthifyMe", website: "https://www.healthifyme.com" },
  { name: "Practo", website: "https://www.practo.com" },
  { name: "PharmEasy", website: "https://pharmeasy.in" },
  { name: "Tata 1mg", website: "https://www.1mg.com" },
  { name: "Netmeds", website: "https://www.netmeds.com" },
  { name: "Cult.fit", website: "https://www.cult.fit" },
  { name: "Lenskart", website: "https://www.lenskart.com" },
  { name: "FirstCry", website: "https://www.firstcry.com" },
  { name: "Pepperfry", website: "https://www.pepperfry.com" },
  { name: "Urban Company", website: "https://www.urbancompany.com" },
  { name: "NoBroker", website: "https://www.nobroker.in" },
  { name: "Housing.com", website: "https://housing.com" },
  { name: "MagicBricks", website: "https://www.magicbricks.com" },
  { name: "99acres", website: "https://www.99acres.com" },
  { name: "Licious", website: "https://www.licious.in" },
  { name: "Country Delight", website: "https://www.countrydelight.in" },
  { name: "ShareChat", website: "https://sharechat.com" },
  { name: "Dailyhunt", website: "https://www.dailyhunt.in" },
  { name: "Dream11", website: "https://www.dream11.com" },
  { name: "Mobile Premier League", website: "https://www.mpl.live" },
  { name: "Games24x7", website: "https://www.games24x7.com" },
  { name: "Nazara Technologies", website: "https://www.nazara.com" },
  { name: "Delhivery", website: "https://www.delhivery.com" },
  { name: "Ecom Express", website: "https://ecomexpress.in" },
  { name: "Shadowfax", website: "https://shadowfax.in" },
  { name: "Porter", website: "https://porter.in" },
  { name: "Shiprocket", website: "https://www.shiprocket.in" },
  { name: "Udaan", website: "https://udaan.com" },
  { name: "Jumbotail", website: "https://www.jumbotail.com" },
  { name: "DeHaat", website: "https://dehaat.com" },
  { name: "Ninjacart", website: "https://ninjacart.com" },
  { name: "Zetwerk", website: "https://www.zetwerk.com" },
  { name: "Infra.Market", website: "https://infra.market" },
  { name: "OfBusiness", website: "https://www.ofbusiness.com" },
  { name: "Moglix", website: "https://www.moglix.com" },
  { name: "Khatabook", website: "https://khatabook.com" },
  { name: "Vyapar", website: "https://vyaparapp.in" },
  { name: "Tracxn", website: "https://tracxn.com" },
  { name: "Wingify", website: "https://wingify.com" },
  { name: "Druva", website: "https://www.druva.com" },
  { name: "Icertis", website: "https://www.icertis.com" },
  { name: "Gupshup", website: "https://www.gupshup.io" },
  { name: "Exotel", website: "https://exotel.com" },
  { name: "Kaleyra", website: "https://www.kaleyra.com" },

  // -------------------------------------------------------------------------
  // Indian banking, financial services and insurance
  // -------------------------------------------------------------------------
  { name: "HDFC Bank", website: "https://www.hdfcbank.com" },
  { name: "ICICI Bank", website: "https://www.icicibank.com" },
  { name: "Axis Bank", website: "https://www.axisbank.com" },
  { name: "Kotak Mahindra Bank", website: "https://www.kotak.com" },
  { name: "State Bank of India", website: "https://www.sbi.co.in" },
  { name: "Punjab National Bank", website: "https://www.pnbindia.in" },
  { name: "Bank of Baroda", website: "https://www.bankofbaroda.in" },
  { name: "Canara Bank", website: "https://canarabank.com" },
  { name: "Union Bank of India", website: "https://www.unionbankofindia.co.in" },
  { name: "IndusInd Bank", website: "https://www.indusind.com" },
  { name: "Yes Bank", website: "https://www.yesbank.in" },
  { name: "IDFC First Bank", website: "https://www.idfcfirstbank.com" },
  { name: "Federal Bank", website: "https://www.federalbank.co.in" },
  { name: "RBL Bank", website: "https://www.rblbank.com" },
  { name: "Bandhan Bank", website: "https://bandhanbank.com" },
  { name: "AU Small Finance Bank", website: "https://www.aubank.in" },
  { name: "HDFC Life", website: "https://www.hdfclife.com" },
  { name: "ICICI Prudential Life Insurance", website: "https://www.iciciprulife.com" },
  { name: "SBI Life Insurance", website: "https://www.sbilife.co.in" },
  { name: "Life Insurance Corporation of India", website: "https://licindia.in" },
  { name: "Max Life Insurance", website: "https://www.maxlifeinsurance.com" },
  { name: "Bajaj Finserv", website: "https://www.bajajfinserv.in" },
  { name: "Bajaj Finance", website: "https://www.bajajfinance.in" },
  { name: "Muthoot Finance", website: "https://www.muthootfinance.com" },
  { name: "Shriram Finance", website: "https://www.shriramfinance.in" },
  { name: "Cholamandalam Investment and Finance", website: "https://www.cholamandalam.com" },
  { name: "L&T Finance", website: "https://www.ltfs.com" },
  { name: "Aditya Birla Capital", website: "https://www.adityabirlacapital.com" },
  { name: "Motilal Oswal", website: "https://www.motilaloswal.com" },
  { name: "ICICI Securities", website: "https://www.icicisecurities.com" },
  { name: "HDFC Securities", website: "https://www.hdfcsec.com" },
  { name: "Angel One", website: "https://www.angelone.in" },

  // -------------------------------------------------------------------------
  // Global banking, markets and payments
  // -------------------------------------------------------------------------
  { name: "JPMorgan Chase", website: "https://www.jpmorganchase.com" },
  { name: "Goldman Sachs", website: "https://www.goldmansachs.com" },
  { name: "Morgan Stanley", website: "https://www.morganstanley.com" },
  { name: "Citi", website: "https://www.citigroup.com" },
  { name: "Bank of America", website: "https://www.bankofamerica.com" },
  { name: "Wells Fargo", website: "https://www.wellsfargo.com" },
  { name: "Barclays", website: "https://www.barclays.com" },
  { name: "HSBC", website: "https://www.hsbc.com" },
  { name: "Standard Chartered", website: "https://www.sc.com" },
  { name: "Deutsche Bank", website: "https://www.db.com" },
  { name: "UBS", website: "https://www.ubs.com" },
  { name: "BNP Paribas", website: "https://www.bnpparibas.com" },
  { name: "Societe Generale", website: "https://www.societegenerale.com" },
  { name: "Nomura", website: "https://www.nomura.com" },
  { name: "Macquarie Group", website: "https://www.macquarie.com" },
  { name: "BlackRock", website: "https://www.blackrock.com" },
  { name: "Fidelity Investments", website: "https://www.fidelity.com" },
  { name: "State Street", website: "https://www.statestreet.com" },
  { name: "BNY Mellon", website: "https://www.bny.com" },
  { name: "Northern Trust", website: "https://www.northerntrust.com" },
  { name: "Visa", website: "https://www.visa.com" },
  { name: "Mastercard", website: "https://www.mastercard.com" },
  { name: "American Express", website: "https://www.americanexpress.com" },
  { name: "Fiserv", website: "https://www.fiserv.com" },
  { name: "FIS", website: "https://www.fisglobal.com" },
  { name: "Global Payments", website: "https://www.globalpayments.com" },
  { name: "D. E. Shaw & Co", website: "https://www.deshaw.com" },
  { name: "Two Sigma", website: "https://www.twosigma.com" },
  { name: "Jane Street", website: "https://www.janestreet.com" },
  { name: "Citadel", website: "https://www.citadel.com" },
  { name: "Optiver", website: "https://optiver.com" },
  { name: "IMC Trading", website: "https://www.imc.com" },
  { name: "Tower Research Capital", website: "https://www.tower-research.com" },
  { name: "WorldQuant", website: "https://www.worldquant.com" },
  { name: "Millennium Management", website: "https://www.mlp.com" },
  { name: "AQR Capital Management", website: "https://www.aqr.com" },
  { name: "Jump Trading", website: "https://www.jumptrading.com" },
  { name: "Quadeye", website: "https://www.quadeye.com" },
  { name: "Graviton Research Capital", website: "https://www.gravitontrading.com" },

  // -------------------------------------------------------------------------
  // Consulting and professional services
  // -------------------------------------------------------------------------
  { name: "McKinsey & Company", website: "https://www.mckinsey.com" },
  { name: "Boston Consulting Group", website: "https://www.bcg.com" },
  { name: "Bain & Company", website: "https://www.bain.com" },
  { name: "Deloitte", website: "https://www2.deloitte.com" },
  { name: "PwC", website: "https://www.pwc.com" },
  { name: "EY", website: "https://www.ey.com" },
  { name: "KPMG", website: "https://kpmg.com" },
  { name: "Grant Thornton", website: "https://www.grantthornton.com" },
  { name: "BDO", website: "https://www.bdo.global" },
  { name: "Kearney", website: "https://www.kearney.com" },
  { name: "Oliver Wyman", website: "https://www.oliverwyman.com" },
  { name: "Roland Berger", website: "https://www.rolandberger.com" },
  { name: "Alvarez & Marsal", website: "https://www.alvarezandmarsal.com" },
  { name: "ZS Associates", website: "https://www.zs.com" },
  { name: "Gartner", website: "https://www.gartner.com" },
  { name: "Forrester", website: "https://www.forrester.com" },
  { name: "Nielsen", website: "https://www.nielsen.com" },
  { name: "Kantar", website: "https://www.kantar.com" },

  // -------------------------------------------------------------------------
  // Core engineering, manufacturing and automotive
  // -------------------------------------------------------------------------
  { name: "Larsen & Toubro", website: "https://www.larsentoubro.com" },
  { name: "Tata Motors", website: "https://www.tatamotors.com" },
  { name: "Mahindra & Mahindra", website: "https://www.mahindra.com" },
  { name: "Maruti Suzuki", website: "https://www.marutisuzuki.com" },
  { name: "Hyundai Motor India", website: "https://www.hyundai.com/in" },
  { name: "Kia India", website: "https://www.kia.com/in" },
  { name: "Toyota Kirloskar Motor", website: "https://www.toyotabharat.com" },
  { name: "Honda Cars India", website: "https://www.hondacarindia.com" },
  { name: "MG Motor India", website: "https://www.mgmotor.co.in" },
  { name: "Tata Steel", website: "https://www.tatasteel.com" },
  { name: "JSW Steel", website: "https://www.jsw.in" },
  { name: "Steel Authority of India", website: "https://www.sail.co.in" },
  { name: "Hindalco Industries", website: "https://www.hindalco.com" },
  { name: "Vedanta", website: "https://www.vedantalimited.com" },
  { name: "Jindal Steel & Power", website: "https://www.jindalsteelpower.com" },
  { name: "Bharat Forge", website: "https://www.bharatforge.com" },
  { name: "Ashok Leyland", website: "https://www.ashokleyland.com" },
  { name: "Eicher Motors", website: "https://www.eichermotors.com" },
  { name: "TVS Motor Company", website: "https://www.tvsmotor.com" },
  { name: "Bajaj Auto", website: "https://www.bajajauto.com" },
  { name: "Hero MotoCorp", website: "https://www.heromotocorp.com" },
  { name: "Royal Enfield", website: "https://www.royalenfield.com" },
  { name: "Ather Energy", website: "https://www.atherenergy.com" },
  { name: "Bosch", website: "https://www.bosch.com" },
  { name: "Siemens", website: "https://www.siemens.com" },
  { name: "ABB", website: "https://global.abb" },
  { name: "Schneider Electric", website: "https://www.se.com" },
  { name: "Honeywell", website: "https://www.honeywell.com" },
  { name: "Emerson", website: "https://www.emerson.com" },
  { name: "Rockwell Automation", website: "https://www.rockwellautomation.com" },
  { name: "General Electric", website: "https://www.ge.com" },
  { name: "Caterpillar", website: "https://www.caterpillar.com" },
  { name: "Cummins India", website: "https://www.cumminsindia.com" },
  { name: "Thermax", website: "https://www.thermaxglobal.com" },
  { name: "Kirloskar Brothers", website: "https://www.kirloskarpumps.com" },
  { name: "SKF India", website: "https://www.skf.com/in" },
  { name: "Godrej & Boyce", website: "https://www.godrej.com" },
  { name: "Voltas", website: "https://www.voltas.com" },
  { name: "Blue Star", website: "https://www.bluestarindia.com" },
  { name: "Havells", website: "https://www.havells.com" },
  { name: "Polycab", website: "https://polycab.com" },
  { name: "Bharat Heavy Electricals", website: "https://www.bhel.com" },

  // -------------------------------------------------------------------------
  // Energy, infrastructure and public sector
  // -------------------------------------------------------------------------
  { name: "NTPC", website: "https://www.ntpc.co.in" },
  { name: "Power Grid Corporation of India", website: "https://www.powergrid.in" },
  { name: "Oil and Natural Gas Corporation", website: "https://www.ongcindia.com" },
  { name: "Indian Oil Corporation", website: "https://iocl.com" },
  { name: "Bharat Petroleum", website: "https://www.bharatpetroleum.in" },
  { name: "Hindustan Petroleum", website: "https://www.hindustanpetroleum.com" },
  { name: "GAIL India", website: "https://www.gailonline.com" },
  { name: "Reliance Industries", website: "https://www.ril.com" },
  { name: "Adani Group", website: "https://www.adani.com" },
  { name: "Adani Green Energy", website: "https://www.adanigreenenergy.com" },
  { name: "Tata Power", website: "https://www.tatapower.com" },
  { name: "Torrent Power", website: "https://www.torrentpower.com" },
  { name: "JSW Energy", website: "https://www.jsw.in/energy" },
  { name: "Suzlon Energy", website: "https://www.suzlon.com" },
  { name: "ReNew", website: "https://www.renew.com" },
  { name: "Indian Space Research Organisation", website: "https://www.isro.gov.in" },
  { name: "Defence Research and Development Organisation", website: "https://www.drdo.gov.in" },
  { name: "Hindustan Aeronautics", website: "https://hal-india.co.in" },
  { name: "Bharat Electronics", website: "https://bel-india.in" },
  { name: "Mazagon Dock Shipbuilders", website: "https://mazagondock.in" },

  // -------------------------------------------------------------------------
  // Semiconductors, hardware and electronics
  // -------------------------------------------------------------------------
  { name: "Texas Instruments", website: "https://www.ti.com" },
  { name: "Analog Devices", website: "https://www.analog.com" },
  { name: "Micron Technology", website: "https://www.micron.com" },
  { name: "Western Digital", website: "https://www.westerndigital.com" },
  { name: "Seagate Technology", website: "https://www.seagate.com" },
  { name: "Broadcom", website: "https://www.broadcom.com" },
  { name: "Marvell Technology", website: "https://www.marvell.com" },
  { name: "Infineon Technologies", website: "https://www.infineon.com" },
  { name: "NXP Semiconductors", website: "https://www.nxp.com" },
  { name: "STMicroelectronics", website: "https://www.st.com" },
  { name: "Renesas Electronics", website: "https://www.renesas.com" },
  { name: "MediaTek", website: "https://www.mediatek.com" },
  { name: "Synopsys", website: "https://www.synopsys.com" },
  { name: "Cadence Design Systems", website: "https://www.cadence.com" },
  { name: "Arm", website: "https://www.arm.com" },
  { name: "Applied Materials", website: "https://www.appliedmaterials.com" },
  { name: "Lam Research", website: "https://www.lamresearch.com" },
  { name: "KLA", website: "https://www.kla.com" },
  { name: "ASML", website: "https://www.asml.com" },
  { name: "GlobalFoundries", website: "https://gf.com" },
  { name: "TSMC", website: "https://www.tsmc.com" },
  { name: "Samsung Electronics", website: "https://www.samsung.com" },
  { name: "LG Electronics", website: "https://www.lg.com" },
  { name: "Sony", website: "https://www.sony.com" },
  { name: "Panasonic", website: "https://www.panasonic.com" },
  { name: "Foxconn", website: "https://www.foxconn.com" },
  { name: "Flex", website: "https://flex.com" },
  { name: "Jabil", website: "https://www.jabil.com" },

  // -------------------------------------------------------------------------
  // Pharmaceuticals, life sciences and healthcare
  // -------------------------------------------------------------------------
  { name: "Sun Pharmaceutical Industries", website: "https://sunpharma.com" },
  { name: "Dr. Reddy's Laboratories", website: "https://www.drreddys.com" },
  { name: "Cipla", website: "https://www.cipla.com" },
  { name: "Lupin", website: "https://www.lupin.com" },
  { name: "Aurobindo Pharma", website: "https://www.aurobindo.com" },
  { name: "Zydus Lifesciences", website: "https://www.zyduslife.com" },
  { name: "Torrent Pharmaceuticals", website: "https://www.torrentpharma.com" },
  { name: "Alkem Laboratories", website: "https://www.alkemlabs.com" },
  { name: "Glenmark Pharmaceuticals", website: "https://glenmarkpharma.com" },
  { name: "Biocon", website: "https://www.biocon.com" },
  { name: "Divi's Laboratories", website: "https://www.divislabs.com" },
  { name: "Mankind Pharma", website: "https://www.mankindpharma.com" },
  { name: "Syngene International", website: "https://www.syngeneintl.com" },
  { name: "Abbott", website: "https://www.abbott.com" },
  { name: "Pfizer", website: "https://www.pfizer.com" },
  { name: "Novartis", website: "https://www.novartis.com" },
  { name: "Roche", website: "https://www.roche.com" },
  { name: "GSK", website: "https://www.gsk.com" },
  { name: "AstraZeneca", website: "https://www.astrazeneca.com" },
  { name: "Sanofi", website: "https://www.sanofi.com" },
  { name: "Johnson & Johnson", website: "https://www.jnj.com" },
  { name: "Merck", website: "https://www.merck.com" },
  { name: "Eli Lilly", website: "https://www.lilly.com" },
  { name: "Bristol Myers Squibb", website: "https://www.bms.com" },
  { name: "Amgen", website: "https://www.amgen.com" },
  { name: "Novo Nordisk", website: "https://www.novonordisk.com" },
  { name: "Takeda", website: "https://www.takeda.com" },
  { name: "Apollo Hospitals", website: "https://www.apollohospitals.com" },
  { name: "Fortis Healthcare", website: "https://www.fortishealthcare.com" },
  { name: "Max Healthcare", website: "https://www.maxhealthcare.in" },
  { name: "Narayana Health", website: "https://www.narayanahealth.org" },
  { name: "Manipal Hospitals", website: "https://www.manipalhospitals.com" },
  { name: "Dr Lal PathLabs", website: "https://www.lalpathlabs.com" },
  { name: "Metropolis Healthcare", website: "https://www.metropolisindia.com" },

  // -------------------------------------------------------------------------
  // Telecom, media, retail and consumer goods
  // -------------------------------------------------------------------------
  { name: "Reliance Jio", website: "https://www.jio.com" },
  { name: "Bharti Airtel", website: "https://www.airtel.in" },
  { name: "Vodafone Idea", website: "https://www.myvi.in" },
  { name: "Bharat Sanchar Nigam", website: "https://www.bsnl.co.in" },
  { name: "Tata Communications", website: "https://www.tatacommunications.com" },
  { name: "Ericsson", website: "https://www.ericsson.com" },
  { name: "Nokia", website: "https://www.nokia.com" },
  { name: "Hindustan Unilever", website: "https://www.hul.co.in" },
  { name: "ITC", website: "https://www.itcportal.com" },
  { name: "Nestle India", website: "https://www.nestle.in" },
  { name: "Britannia Industries", website: "https://www.britannia.co.in" },
  { name: "Dabur", website: "https://www.dabur.com" },
  { name: "Marico", website: "https://marico.com" },
  { name: "Godrej Consumer Products", website: "https://www.godrejcp.com" },
  { name: "Emami", website: "https://www.emamigroup.com" },
  { name: "Colgate-Palmolive India", website: "https://www.colgatepalmolive.co.in" },
  { name: "Procter & Gamble", website: "https://www.pg.com" },
  { name: "Unilever", website: "https://www.unilever.com" },
  { name: "PepsiCo", website: "https://www.pepsico.com" },
  { name: "Coca-Cola", website: "https://www.coca-colacompany.com" },
  { name: "Mondelez International", website: "https://www.mondelezinternational.com" },
  { name: "Amul", website: "https://amul.com" },
  { name: "Parle Products", website: "https://www.parleproducts.com" },
  { name: "Tata Consumer Products", website: "https://www.tataconsumer.com" },
  { name: "Asian Paints", website: "https://www.asianpaints.com" },
  { name: "Berger Paints", website: "https://www.bergerpaints.com" },
  { name: "Pidilite Industries", website: "https://www.pidilite.com" },
  { name: "UltraTech Cement", website: "https://www.ultratechcement.com" },
  { name: "Ambuja Cements", website: "https://www.ambujacement.com" },
  { name: "Shree Cement", website: "https://www.shreecement.com" },
  { name: "Dalmia Bharat", website: "https://www.dalmiabharat.com" },
  { name: "Avenue Supermarts", website: "https://www.dmart.in" },
  { name: "Reliance Retail", website: "https://relianceretail.com" },
  { name: "Trent", website: "https://www.trentlimited.com" },
  { name: "Shoppers Stop", website: "https://www.shoppersstop.com" },
  { name: "Titan Company", website: "https://www.titancompany.in" },
  { name: "Bata India", website: "https://www.bata.in" },
  { name: "Page Industries", website: "https://www.jockeyindia.com" },
  { name: "Aditya Birla Fashion and Retail", website: "https://www.abfrl.com" },
  { name: "Raymond", website: "https://www.raymond.in" },
];
